baseURL: /hugo-theme-mild/
# Local Dev
# When using / in Site.BaseURL it will return "//localhost:1313/" 
# Read more: https://discourse.gohugo.io/t/localhost-github-pages-mismatch/31905/3
# baseURL: /
languageCode: en
DefaultContentLanguage: en
theme: hugo-theme-mild
title: Mild
enableInlineShortcodes: true
enableEmoji: true
googleAnalytics: ""
params:
  lazyImage: true
  enableMathJax: false
  enableReadingTime: true
  favicon: favicon.ico
  startyear: "2019"
  description: A simple and concise hugo theme.
  disqus: ""
  valine:
    enable: false
    lang: en
    appId: ""
    appKey: ""
    placeholder: Say Something......
    requiredFields:
      - nick
      - mail
    avatar: robohash
    visitor: true
    serverURLS: https://abc123.api.lncldglobal.com
    debug: false
menu:
  main:
    - name: Posts
      url: posts/
      weight: 1
    - name: Talks
      url: talks/
      weight: 2
  extend:
    - name: Tags
      url: tags/
      weight: 3
social:
  github: https://github.com/mildronize
  rss: index.xml
taxonomies:
  category: categories
  tag: tags
# A must config for remove all style from code highlight
# To be use with Prism JS.
markup:
  highlight:
    noClasses: false