# Lighthouse-Badger-Easy | GitHub Action Workflow
# 
# Description: Generates, adds & updates manually/automatically Lighthouse badges & reports from one/multiple input URL(s) to the current repository & main branch with minimal settings
# Author: Sitdisch
# Source: https://github.com/myactionway/lighthouse-badger-workflows
# License: MIT
# Copyright (c) 2021 Sitdisch

name: 'Lighthouse Badge Build'

env:
  URLS: https://thadaw.com/hugo-theme-mild/ # URL(s) to be checked e.g. 'https://github.com/sitdisch https://github.com/mythemeway'
  TOKEN_NAME: LIGHTHOUSE_BADGER_TOKEN # target token name; insert only the name never the real value e.g. 'LIGHTHOUSE_BADGER_TOKEN'
  REPO_BRANCH: '${{ github.repository }} main' # target repo & branch
  output_branch: 'lighthouse'

on:
  workflow_run:
    workflows:
      - "Build GitHub Pages"
  workflow_dispatch:

jobs:
  lighthouse-badger-easy:
    if: >-
      github.event_name == 'workflow_dispatch' ||
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-20.04
    steps:
      - name: Preparatory Tasks
        run: |
          REPOSITORY=`expr "${{ env.REPO_BRANCH }}" : "\([^ ]*\)"`
          BRANCH=`expr "${{ env.REPO_BRANCH }}" : ".* \([^ ]*\)"`
          echo "REPOSITORY=$REPOSITORY" >> $GITHUB_ENV
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          repository: ${{ env.REPOSITORY }}
          token: ${{ secrets[env.TOKEN_NAME] }}
          ref: ${{ env.BRANCH }}
          
      - uses: actions/checkout@v3
        with:
          repository: 'myactionway/lighthouse-badges'
          path: temp_lighthouse_badges_nested

      - name: Switch to output branch
        run: |
          git fetch
          git switch ${{ env.output_branch }}

      - uses: myactionway/lighthouse-badger-action@v2.2
        with:
          urls: ${{ env.URLS }}
        env:
          BRANCH: ${{ env.output_branch }}